### ISSUE TITLE
Persistent option will reload graph which prevents y scrolling

### ISSUE THREAD

**Issue by felixhayashi** [kixam/TW5-visjsTimeline#12]
Hi @kixam 

the persistent option is a great feature!!

The problem is, the graph reloads once dragndrop stops and when I moved the y axis it immediately gets reset. Maybe set a flag in the widget instance where the drop action occurs that prevents a refresh for this widget because it is not necessary to reload the widget/options in this case...

Thanks
-Felix

**Comment by kixam** [comment]
thank you for finding this bug

unfortunately, it might be a difficult one... vertical position is not accessible via vis.js at all, so I might have to tweak a lot, maybe for a poor result... Anyway, I will look into this.

**Comment by felixhayashi** [comment]
As said above, when persistent is active, an option is to set a flag `this.doNotRefresh = true` after the timeline viewport was moved. And inside `refresh()` check for this flag and set it to `false` after the next refresh. Then only widgets (in the river) will be refreshed where the viewport wasn't dragged. 

I use a variant of this technique for tiddlymap to avoid viewport resets when a node was dragged in one graph. Then only other graphs repaint/refresh but not the active one.

hmm just thinking, maybe it doesn't work for you because you store the parameters in the fields of the same tiddler that holds the widget... I don't know...

I am sure you'll figure out a better solution anyways :)

-Felix

**Comment by kixam** [comment]
> I am sure you'll figure out a better solution 

Thanks for the vote of trust, I wish I was as confident as you are!

**Comment by kixam** [comment]
it seems that, whenever I save a parameter, I trigger an all-out refresh (triggers `$tw.wiki` `change` event), which calls not `timeline.refresh()` but no less than `timeline.render()`... Am I supposed to rewrite the `addTiddler` function to block the refresh process? I could not even find it in the `$core` plugin...

I am trying to save the vertical offset at least when a `navpad` button is clicked, and listen to the `$tw.wiki` `change` event to reapply it (or, for the moment, apply the setting I put manually...). According to the logs, it is supposed to work, but something else must execute even after that, because the property gets reverted anyway... I am suspecting maybe a remainder of some event handler inherent to `vis.js`...

I do not want to save the persistent data elsewhere, because to me it belongs to the containing tiddler, but I might try to save it somewhere else, if I must choose between that or drop the `persistent` attribute altogether.

Anyway, as you may have guessed, for the moment I am at a loss. I will keep trying; in the meantime, do not hesitate to send me your thoughts on the matter!

**Comment by felixhayashi** [comment]
Hi @kixam 

It is hard for me to debug this at the moment.

> which calls not timeline.refresh() but no less than timeline.render()

If only render is called and not refresh this means that your plugin is completely refreshed (either from outside because the parent widget was completely rebuild or, in your case more likely: because it called refreshSelf). In this case refresh is not called anymore...

> Am I supposed to rewrite the addTiddler function to block the refresh process?

There is no chance that you can prevent a refresh to happen in tiddlywiki, and overriding core functions will break tw so this is also not the solution :)

A better solution (and this is what you are actually aiming at as far as I understand it) is to ignore certain changes during refresh. 

Probably the only chance here to discover the problem is plain-old adding console logs and step-by-step removing functions to see where the problem lies :(

-Felix

P.S.

When opening the console in the demo site I get a message `WARNING: infinite loop in redraw?`

**Comment by kixam** [comment]
hi @felixhayashi ,

> Probably the only chance here to discover the problem is plain-old adding console logs and step-by-step removing functions to see where the problem lies :(

this is exactly how I have been proceeding. I will keep you posted on any progress I make.

> When opening the console in the demo site I get a message WARNING: infinite loop in redraw?

I will check this

**Comment by felixhayashi** [comment]
> I will keep you posted on any progress I make.

Ok, of course I try to help you were it is possible, but I am missing the time for actual debugging – but maybe I can help you out with theoritical answers to tiddlywiki/vis questions.

**Comment by kixam** [comment]
hi @felixhayashi , 

I was giving an update to all the people interested in this bug.

> I can help you out with theoritical answers

yes, that is more than enough support for me. This plugin is a hobby to me. I enjoy challenges, and learning in the process of solving them. Do not spend too much time in coding spoiling solutions ;)

> of course I try to help you were it is possible

I believe your spare time is better spent on your own plugins, before the other's ;) but of course I am always glad to have your advice. Thanks for your support!

> I am missing the time for actual debugging

during summer, I also have limited time to spend on this

**Comment by felixhayashi** [comment]
Just one thought, probably unrelated but do you call the destroy function (destructor) of the timeline when the widget is removed? Maybe some listeners remain..

**Comment by felixhayashi** [comment]
Sorry, it was late and I completely oversaw you last post.

> This plugin is a hobby to me. I enjoy challenges, and learning in the process of solving them.

Great to hear that! From what I have seen, you are highly experienced so you will certainly come up with good solutions. Your way of doing it is also of interest for me, I might steal some of your code ;)

> I believe your spare time is better spent on your own plugins, before the other's ;) but of course I am always glad to have your advice. Thanks for your support!

Ok, you are right, I just felt that I am a bit responsible because I originally suggested you pick up the development of this plugin.

> during summer, I also have limited time to spend on this

Yes, very true! Better enjoying the sunny days!

-Felix
