### ISSUE TITLE
timeline:start timeline:end characters

### ISSUE THREAD

**Issue by felixhayashi** [kixam/TW5-visjsTimeline#14]
Hi @kixam 

I suggest you name it `timeline.start` `timeline.end` as colons are not allowed: http://tiddlywiki.com/#TiddlerFields. Colons become really problematic if you think about how tiddlywiki saves fields in node.js using the *.tid format: `name:value` so it would save `timeline:start: 2015-07-09T16:40:59+02:00`. And what happens at next loading? It will render as fieldname `timeline` and value `start: 2015-07-09T16:40:59+02:00` :(

I also had to learn the hardway not to store uppercase field names (a similar problem).

-Felix

**Comment by kixam** [comment]
I don't know, it works for me for another purpose (no relation to this plugin), and it is a good way to make sure no normal user can create the field (=> no confusion with user's fields).

Also, it seems to work for timeline plugin so far.

I agree it might be a dangerous game to play though. I will think about it.

**Comment by felixhayashi** [comment]
I agree. I would love to use colons like you do since it looks like a beautiful namespace but it creates big trouble with node.js

> Also, it seems to work for timeline plugin so far.

Nope. With the widget running in node.js (many people do it) it doesn't work. it will append "start" to the time when reloading.

> I agree it might be a dangerous game to play though.

Yeah dangerous!!

![1c18235e43011a05ef680fb81435bab2](https://cloud.githubusercontent.com/assets/4307137/8553783/0ba2cdd8-24e6-11e5-8a50-24414e34226a.jpg)

**Comment by kixam** [comment]
> With the widget running in node.js

I still need to figure out how to run TW5 in server mode under node.js or nw.js ... seems to be a prerequisite to solving this one. about time too. I needed a good excuse I guess (or a kick in the butt?). there I am.

**Comment by felixhayashi** [comment]
> there I am.

Hi @kixam 

there are several ways to run tw with nodejs.

This is the setup I am using:

say you are in directory `/my/path/`
1. clone the tiddlywiki github repo to `/my/path/tw5/`
2. now to create an empty wiki create a directory somewhere e.g. `/my/path/mywiki/`
3. copy the `tiddlywiki.info` file from `/my/path/tw5/editions/server/` to `/my/path/mywiki/`
4. assuming you are in a bash run (relative paths are fine too)

``` bash
interpreterPath="/my/path/tw5/tiddlywiki.js"
wikiRootPath="/my/path/mywiki/"
node $interpreterPath $wikiRootPath --verbose --server 8081
```

To add plugins
1. say your plugins are stored here `/my/path/plugins/`
2. clone your timeline plugin etc. below `/my/path/plugins/`
3. for each plugin create a symlink to the actual plugin folder and put the symlink into `/my/path/tw5/plugins`
4. e.g 
   
   ![selection_391](https://cloud.githubusercontent.com/assets/4307137/8566853/4b74e218-2561-11e5-8702-1aac9035c15d.png)
5. In your tiddlywiki.info file add the plugins like this
   
   ```
   {
     "plugins": [
       "tiddlywiki/github-fork-ribbon",
       "tiddlywiki/tiddlyweb",
       "tiddlywiki/filesystem",
       "tiddlywiki/highlight",
       "felixhayashi/topstoryview",
       "felixhayashi/hotzone",
       "felixhayashi/vis",
       "felixhayashi/tiddlymap",
       "danielo/contextPlugin",
       "kixam/timeline",
       "kixam/moment"
     ],
     "themes": [
       "tiddlywiki/vanilla"
     ],
     "languages": [
       "en-US"
     ],
     "build": {
       "index": ["--rendertiddler","$:/core/save/all","index.html","text/plain"]
     },
     "config": {
       "retain-original-tiddler-path": true
     }
   }
   ```
6. restart the server

Hope it helps
-Felix

**Comment by kixam** [comment]
> node $interpreterPath $wikiRootPath --verbose --server 8081

This is all I missed, I already have all the rest, thanks !
