### ISSUE TITLE
Bug with boxing=auto and display tiddler

### ISSUE THREAD

**Issue by silvyn** [kixam/TW5-visjsTimeline#15]
Hello,

With boxing=auto option, there is a visual bug on a tiddler, for exemple : 

![hauteur-timeline-tiddler](https://cloud.githubusercontent.com/assets/9981592/8574365/8fe6fffa-2596-11e5-89a4-c58045473f91.png)

**Comment by kixam** [comment]
thanks for discovering this bug. I will look into it.
