### ISSUE TITLE
Order list groupTags

### ISSUE THREAD

**Issue by silvyn** [kixam/TW5-visjsTimeline#16]
Hi,

Do you know how to order our tag group ?

I have a filter visualisation with 3 tags, but don't use my order list, for example : 

`groupTags=[[C_tag1]][[L_tag2]][[R_tag3]]`

> render as : 
> - C_tag1
> - R_tag3
> - L_tag2

I don't know if we can use list ou list-before/after option.

Thanks.

**Comment by kixam** [comment]
good question. it was supposed to keep the order you provided? it does it for me... it is the order I transmit to  `vis.js` anyway. I will see if I can do something about this.
