### ISSUE TITLE
[Question] Config Example

### ISSUE THREAD

**Issue by nicholaslacasse** [kixam/TW5-visjsTimeline#17]
I cannot get the timeline config to work. Could a full example be provided on the demonstration tiddlywiki?

My timeline tidder has the following inside of it:

```
<$visjstimeline filter="[tag[Timeline]]" startDateField="born" endDateField="died" format="YYYY" config="myconfig" />
```

My config tiddler is titled "myconfig" it's type is "application/json" and its contents (and likely the source of the issue) are:

```
{
  "orientation": 'none'
}
```

I do not have any experience with JSON, but I have been looking around a bit and tried many variations of formatting but nothing seems to work. Also, I'm trying to hide the timeline axis (as a workaround to not being able to add in BCE dates).

**Comment by kixam** [comment]
hi, you need double quotes for both identifier and value (see [here](http://tiddlywiki.com/#JSONTiddlers)). Please try this and let me know about the outcome:

```
{
  "orientation": "none"
}
```

**Comment by nicholaslacasse** [comment]
That solved the problem! Thank you very much! :)
