### ISSUE TITLE
suggestion: created / modified should not be used to draw tiddlers as bars

### ISSUE THREAD

**Issue by pmario** [kixam/TW5-visjsTimeline#2]
eg: If I create a tiddler today it creates a very tiny bar with no text. Only if I set created and modified to the exact same timestamp I get a "dot" with the tiddler name. 

If I create a tiddler today and modify it in one year, it will create a very long bar. 

IMO this behaviour should be revised.

**Comment by kixam** [comment]
Thank you for your comment.

Actually, it is up to you to specify other fields for the widget to use, by passing startDateField and/or endDateField parameters to the widget.

Also, endDateField is optional, and if it is not specified, you will only get "dot" type items in your timeline, and no "bar" type, as only one date will be used.

**Comment by pmario** [comment]
If I use: `<$visjstimeline endDateField="modified" groupTags="[[Group A]]" startDateField="created"  navpad>`

it doesn't work. ... This issue is closed. should I open a new one?

**Comment by kixam** [comment]
Please describe what does not work to you in more details.

According to your example, I think you might have posted in the wrong thread. Did you mean to post in issue #3 ?

**Comment by pmario** [comment]
Using: `<$visjstimeline endDateField="modified" groupTags="[[Group A]]" startDateField="created" navpad>`  I did expect, that every element in the timeline is just a dot. 

You wrote, that `endDateField` is optional. Since every tiddler has a created field, there should be just dots. right?

**Comment by kixam** [comment]
hi @pmario 

if you do not want any bars, but only dots, you should not use the `endDateField` parameter at all, like so:

`<$visjstimeline groupTags="[[Group A]]" startDateField="created" navpad>`

or, since `startDateField` has value `created` by default, in this case the following would give you the same result:

`<$visjstimeline groupTags="[[Group A]]" navpad>`

**Comment by pmario** [comment]
hi, I'm sorry. I completely missed the endDtateField definition in my wildget call. I did expect the parameter at the end of the call. I just didn't see it. :)
