### ISSUE TITLE
Show start and end in the description hover

### ISSUE THREAD

**Issue by UXlibrarian** [kixam/TW5-visjsTimeline#22]
Hello! I've been enjoying putting your plugin through the paces. It's very impressive. My question is in regards to show the start/end in the hover. I have 268 people in my timeline and it's a little difficult to tell their birth/death since it doesn't clearly show on the timeline itself. While it is simple enough to click on their name to open their tiddler, I thought it'd be even easier if the description hover just pulled in the start/end automatically. 

Do you know if there is a way to dynamically pull in that data from the custom start/end fields?

**Comment by kixam** [comment]
hi @UXlibrarian,

ATM there is none, but I am looking into it.
