### ISSUE TITLE
Bug with persistent (or with option config tiddler)

### ISSUE THREAD

**Issue by silvyn** [kixam/TW5-visjsTimeline#23]
Hello @kixam 

If you read the forum, I"ve poke you about a question on how to made a persistent view. I've tested with your usage doc, and if I've succed once, but I have a bug on my timeline after.

https://forum.tiddlywiki.fr/t/timeline-comment-definir-une-vue-de-depart/182/4?u=sylvain

Maybe I don't use config json option correctly. Do you have a demo example ?

I upload my demo wiki of DatePicker and Timeline here if you want to look after : 

http://tw5.xyz/TiddlyWiki-DatePicker-Timeline_v5.1.13.html

**Comment by kixam** [comment]
Hi, I am a bit "unplugged" during summer, I will look into it ASAP

**Comment by ghost** [comment]
Hi, 
I've updated this plugin to see if this problem had been solved but it seems not. Is there some sort of temporary workaround while the problem is adressed?

**Comment by kixam** [comment]
hi @Acknar ,

Sorry but I cannot find a solution to this issue. I thought I had solved it in the past, and it occurred that I did not really. Now, I would need to go yet deeper into TW and vis.js refresh mechanisms, but my work is taking me too much brain/time ATM. I would be happy to take any advice or merge any improving code that you users might have though.

In the meantime, maybe you could use TW filters to display a selection of events, like [demonstrated here](https://github.com/kixam/TW5-visjsTimeline/issues/21). Unfortunately I do not know how to do maths with dates for now, so you would have to use tags such as "2016-12", or "December" and "2016" and such.

Maths with dates (add/subtract, and compare) should be possible with my moment.js plugin loaded, using user-defined Javascript macros, but I have no example to show, if you make something work please share with the community. This could allow for advanced filtering, and potentially enable the permaview functionality from outside the plugin, hence circumventing the bug.

**Comment by ghost** [comment]
Thanks for the reply. I'm afraid my coding knowledge is more than insufficient for this level of programming so i'll just display the full timeline for now. If I ever find a way to work around this bug, i'll be sure to post a message here :)

**Comment by kixam** [comment]
Hi everybody,

I have come up with a better workaround that I hope might satisfy some of you. The idea is to filter out tiddlers that are out of target scope from the timeline, and dynamically select said scope by using 2 fields of the calendar tiddler.

1. For people who need a timeline bound by arbitrary dates, I tested the following:

1.1. install my [datepicker plugin](https://github.com/kixam/TW5-datePicker)

1.2. add the attached tiddler to implement new filters `earlier` and `later`

[$__kixam_filters_earlierlater.js.tid.zip](https://github.com/kixam/TW5-visjsTimeline/files/706825/__kixam_filters_earlierlater.js.tid.zip)

1.3. create a blank tiddler and use this for its body. In this example, I titled the tiddler "Calendar".

```
<div style="position:relative;">
<div style="position:absolute;top:5px;left:5px;z-index:999;padding-top:2px;padding-left:10px;padding-right:10px;background-color:rgba(100,200,100,.1);border-radius:25px;box-shadow:1px 1px 2px">
Start: <$edit-date tiddler=Calendar field=start/>
End:<$edit-date tiddler=Calendar field=end/>
</div>
<$visjstimeline filter="[earlier:end{Calendar!!end}later:start{Calendar!!start}]" startDateField="start" endDateField="end"/>
</div>
```

2. For people who need a timeline bound by an arbitrary number of days relative to current day (time is ignored), please try the following, I did not test it thoroughly but I hope it gets you started.

2.1. Use the following code as body:

```
<div style="position:relative;">
<div style="position:absolute;top:5px;left:5px;z-index:999;padding-top:2px;padding-left:10px;padding-right:10px;background-color:rgba(100,200,100,.1);border-radius:25px;box-shadow:1px 1px 2px">
Start: <$edit-text tiddler=Calendar field=start/>
End:<$edit-text tiddler=Calendar field=end/>
</div>
<$visjstimeline filter="[days:end{Calendar!!end}days:start{Calendar!!start}]" startDateField="start" endDateField="end"/>
</div>
```

2.2. the fields should contain a number of days. Please check the official documentation for the [days operator](http://tiddlywiki.com/#days%20Operator)

Please tell me how it works for you

**Comment by ghost** [comment]
I tried the first method and it works although i'm not exactly convinced by the functionnality. 
Since the timeline is dynamic, I expected to see the filter automatically change to fit the zoom (but in hindsight, I imagine that must be impossible or at least quite difficult to implement).  
Filling in the dates at the top works only once refreshed.
The filter eleminates a lot of my tiddlers that span over long periods of time since their start and end dates don't entierly fit entierly into the filter.
