### ISSUE TITLE
hiddenDates

### ISSUE THREAD

**Issue by K0ertis** [kixam/TW5-visjsTimeline#24]
Hi! I am trying to add the option "hiddenDates". My tiddler (application/json) "TimeConfig" looks like: 

``` javascript
var options = {
  hiddenDates:{
    start: '2016-09-03 00:00:00', 
    end: '2016-09-05 00:00:00',
    [repeat:'weekly']
  }
};
```

my Timeline looks like: 

``` javascript
<$visjstimeline filter="[field:gsd_type[action]]" endDateField="tend" config="TimeConfig">
```

I have tried forgivingly to switch to the other date format which I am using in my Timeline : `20160903000000000`
If I edit the timeline again to update it, nothing happens. What am I doing wrong? None of my configs from your _whitelist_ works.
Other question:
Do I need to add persistent to the Config tiddler too?

Grid Backgrounds would be great, will this option be possible in the future?
Best regards,

**Comment by kixam** [comment]
hi @K0ertis,

you need to manually set TimeConfig tiddler as "application/json" in the dropdown list at the bottom of the edit mode frame.

then, this tiddler has to contain only valid JSON. In your case, that would be:

```
 { "hiddenDates": {
    "start": "2016-09-03 00:00:00", 
    "end": "2016-09-05 00:00:00",
    "repeat": "weekly"}}
```

your errors:
- `var options =` is JavaScript, not JSON; also, the plugin already assumes that the entire content of your tiddler is `options`;
- in JSON, all key names, as well as all non-boolean or number values,  _must_ be wrapped in double quotes. Simple quotes are never allowed;
- you cannot define a dictionary entry without a key like you did for `[repeat ...]`
- in vis.js documentation, they use `[ ]` brackets to emphasize that `repeat` is optional. This is common in documentations; you are not supposed to keep them.

please tell me if it helped

[edit] fixed typo

**Comment by K0ertis** [comment]
Hi! Thank you very much for this explanation, now it works. In your example there is a simple quote before **2016-09-03 00:00:00** too much.
How can I add a second statement to eliminate the hours between 19:00 and 07:00 daily. It will not work like that:

```
[{ "hiddenDates": {
    "start": "'2016-09-03 00:00:00", 
    "end": "2016-09-05 00:00:00",
    "repeat": "weekly"}},
{ "hiddenDates": {
    "start": "'2016-09-02 19:00:00", 
    "end": "2016-09-03 07:00:00",
    "repeat": "daily"}}]
```

```
[{ "hiddenDates": {
    "start": "'2016-09-03 00:00:00", 
    "end": "2016-09-05 00:00:00",
    "repeat": "weekly"},
    {"start": "'2016-09-02 19:00:00", 
    "end": "2016-09-03 07:00:00",
    "repeat": "daily"}}]
```

**Comment by kixam** [comment]
according to visjs.org documentation, you are almost there.

> The dates can be supplied as an object: `{start: '2014-03-21 00:00:00', end: '2014-03-28 00:00:00', [repeat:'daily']}` or as an Array of these objects.

I think this would work:

```
{ "hiddenDates": [{
    "start": "2016-09-03 00:00:00", 
    "end": "2016-09-05 00:00:00",
    "repeat": "weekly"},
    {"start": "2016-09-02 19:00:00", 
    "end": "2016-09-03 07:00:00",
    "repeat": "daily"}]}
```

remember config must be a dictionary `{ }`, not an array `[ ]`
