### ISSUE TITLE
moment.js plugin version differs from DatePicker's one

### ISSUE THREAD

**Issue by mauloop** [kixam/TW5-visjsTimeline#26]
Hi, Kixam.

I would like to add visjsTimeline plugin to my wiki, which also makes use of DatePicker plugin. I have moment.js plugin already installed, since it was required by DatePicker. I see that moment.js rel provided with visjsTimeline is 2.23.0, while the one I installed with DatePicker was 2.18.1.

Is it safe to update moment.js and have both DatePicker and visjsTimeline installed in the same wiki?

Thanks for your help and for your great work,

)+(auloop

**Comment by kixam** [comment]
Hi @mauloop ,

I think it should, but I do not know of any other plugin that has moment.js as a dependency, so it really is not necessary to update it. I will rebuild all demos with the latest plugins for peace of mind.
