### ISSUE TITLE
confusing error popup looks like crash popup

### ISSUE THREAD

**Issue by pmario** [kixam/TW5-visjsTimeline#3]
To reproduce: 

Change content of `Demonstration` tiddler to 

```
<$visjstimeline endDateField="modified" groupTags="[[Group A]]" startDateField="start" endDateField="end" navpad>
```

**Comment by kixam** [comment]
Thank you for your comment.

If you look closely, it is not a final and general crash, but rather an error message with the list of issues the plugin found in your call. In emkay's plugin which I continued, errors were permanently and statically displayed above the timeline, and I wanted the user to be able to discard an error message and see what worked even if something went wrong.

Now then, I agree I should not use the same style as the crash window, that was just shorter for me to copy/paste code from the core, but I should really change the style of this popup.

Now that you know the background, do you think its styling is all that makes this popup confusing?
