### ISSUE TITLE
feature request: timeline x-position and zoom level should be persistent

### ISSUE THREAD

**Issue by pmario** [kixam/TW5-visjsTimeline#4]
As the title says: It would be nice if: timeline x-position and zoom level should be persistent

**Comment by kixam** [comment]
Thank you for your comment.

It seems feasible but a bit difficult. Also, you might want to take into account how to render any modification on the timeline due to an external event (add/remove tiddler, change some date, ...) - or not. I might investigate.

**Comment by kixam** [comment]
fixed by 9c3f6635558118a201833df352c92a6cda0fd57d

**Comment by pmario** [comment]
thx
