### ISSUE TITLE
Plugin path

### ISSUE THREAD

**Issue by felixhayashi** [kixam/TW5-visjsTimeline#5]
Hi @kixam 

would you mind renaming your directory path `plugins/visjsTimeline` into `plugins/timeline` so it matches with the prefix you also use in your tiddler titles? (Same for `kixam/momentjs` vs. `kixam/moment`). It confused me when I wanted to add the plugins to my tiddlywiki.info file...

Thanks!

-Felix

**Comment by kixam** [comment]
done in 4a791961ee3c0c1d44672a22a88abf975cfb5d2d

**Comment by felixhayashi** [comment]
thanks
