### ISSUE TITLE
Moving v4 github files to separate branch?

### ISSUE THREAD

**Issue by felixhayashi** [kixam/TW5-visjsTimeline#6]
Hola Kixam,

just noticed that using the github version on master you already switched to Vis v4.0

So I guess I need to install the plugin via drag n drop from your demo then...

Just if you find the time it would be nice if you could move the commits starting from https://github.com/kixam/TW5-visjsTimeline/commit/c662067e2ae805b47585494d05d885687763f700 to a separate "develop" branch or "v4"? I still need time to migrate to v4 as many bugs appear and even though the developers at vis.js fix all my issues impressively fast, it continues to be a slow process as much changed in the network api :(

-Felix

P.S. Again really great job on the plugin development! I am glad a skilful programmer picket it up :)

**Comment by kixam** [comment]
Hi @felixhayashi 

Actually I moved on to vis 4.1.0, but like promised, I did not push the index.html on gh-pages branch, so the main website is still back in 3.12.0.

Honestly, I do not want to develop new features for a deprecated vis.js, even less since the API changed so much.

But I agree it is confusing to keep new features in the master branch, as the vis.js 4.1.0 plugin is not yet officially available. So, I may comply. I need to have a look in git doc ;-)

**Comment by felixhayashi** [comment]
> Honestly, I do not want to develop new features for a deprecated vis.js, even less since the API changed so much.

No of course not! this is not what I meant. Just wanted to highlight that people who try to install from git will be facing errors.

> I need to have a look in git doc ;-)

I think you'll need to checkout your current repo as new branch (e.g. "v4") and then make master point to the 6.0.0 commit (git reset --hard). But I am also not a git guru :D Better verify, make backups and if it is too cumbersome, please just ignore my issue!

**Comment by kixam** [comment]
I'm sorry, after some investigation, it seems to be a hassle. Creating a new branch from an old commit is piece of cake, but then it is not possible to delete commits from the master branch, so I should have to create a "mirror commit" that would revert all commits in master back to c662067e2ae805b47585494d05d885687763f700, but it will be very confusing to everyone, even me... especially when I will commit a "mirror of the mirror" to merge the dev branch into master...

Sorry, I should have created a branch right away when you said you needed time... I will know for next time.

In the meantime, people using **ONLY** timeline could pull [my fork of your vis.js plugin](https://github.com/kixam/TW5-Vis.js.git]) ...

People using both will have to either revert their repo to c662067e2ae805b47585494d05d885687763f700, [download the zip snapshot of the last release](https://github.com/kixam/TW5-visjsTimeline/archive/v0.6.0.zip), or drag and drop from the [demo website](http://kixam.github.io/TW5-visjsTimeline/) and be patient...

**Comment by felixhayashi** [comment]
> I'm sorry, after some investigation, it seems to be a hassle.

Ah that sucks. Sorry for asking then. I think the options you offered in your last post are fine.
