### ISSUE TITLE
Option Management + Allowing to define the granularity/scale of the time axis

### ISSUE THREAD

**Issue by felixhayashi** [kixam/TW5-visjsTimeline#7]
It would be nice if the granularity of the time axis could be defined via attribute.

Property "timeAxis" @ http://visjs.org/docs/timeline/#Configuration_Options

One Idea for option management would be to allow the user to reference json tiddlers that are then injected using `setOptions` at instantiation time.

So a user creates a tiddler named "MyTimelineConfig"

```
{
  "clickToUse": true,
  "height": "30px",
  "timeAxis": {"scale": 'minute', "step": 5}
}
```

And references the config

```
<$visjstimeline startDateField="modified" groupTags="[tag[Literature]]" config="MyTimelineConfig" navpad />
```

And the plugin simply parses the json and injects it as options

```
timeline.setOptions($tw.wiki.getTiddlerData("MyTimelineConfig", {}));
```

This way you do not have to create an attribute for every option and pass the responsibility of handling options to the user which will certainly save you much time ;)

-Felix

**Comment by kixam** [comment]
Hi @felixhayashi 

Thank you for your suggestion.

I think that, from a TiddlyWiki user's viewpoint, the feature of presetting the granularity is close to the feature proposed in #4. Actually, to implement #4, I was thinking of creating fields in the containing tiddler such as `timeaxis:start` and `timeaxis:end`, which would, together with the available width, automatically and smoothly decide the time scale. And not the other way around. But maybe this is too much related to my own experience of TiddlyWiki?

Generally speaking, in order to better prevent bugs, inconsistencies, or redundancy/conflict between vis.js and TiddlyWiki, I would rather integrate options one by one than giving a direct access to the underlying library.

If some user wants to display any random timeline, they do not need emkay's plugin, your vis.js plugin is enough, then they just have to write a simple macro in javascript and voilà.

**Comment by felixhayashi** [comment]
Hi @kixam 

> which would, together with the available width, automatically and smoothly decide the time scale.

Problem here is that I want to display always the current time ("now") but just on a finer grained scale. WIth your proposed solution, this would mean I always have to change `timeaxis:start/end` just to adjust the scale.

> Generally speaking, in order to better prevent bugs, inconsistencies, or redundancy/conflict between vis.js and TiddlyWiki, I would rather integrate options one by one than giving a direct access to the underlying library.

That is reasonable but I think that you will encounter a bunch difficulties with this strategy:
- How to deal with nested vis.js options like margin? You will have to make them "flat" in order to use them as widget attributes.
- Vis.js option names are camel case and will differ from your option names.
- You will have to provide custom documentation in contrast to simply pointing to vis.js documentation on options because your option names differ from the original ones.
- When vis.js changes or adds options, you are "responsible" for adding them one by one because the user has no chance to do so.
- In the end, you are just recreating the vis options with different names causing much extra work for yourself.

> If some user wants to display any random timeline, they do not need emkay's plugin, your vis.js plugin is enough, then they just have to write a simple macro in javascript and voilà.

Correct. But just because a user wants to have the timeline displayed with certain options it doesn't mean it becomes random :) Your timeline plugin is great and of course you are right that not all vis options make sense for the timeline plugin in combination with tiddlywiki. But you can always ignore certain options by overriding them.

Anyways, you are the master of your plugin. But I would be really happy to be able to adjust margin values of the items and the timeaxis. I hope this will be feasible at some point :)

-Felix

**Comment by kixam** [comment]
Hi @felixhayashi 

> I want to display always the current time ("now")

Thank you, now I understand how different from #4 this is: it is the opposite indeed.

> > Generally speaking, in order to better prevent bugs, inconsistencies, or redundancy/conflict between vis.js and TiddlyWiki, I would rather integrate options one by one than giving a direct access to the underlying library.
> 
> That is reasonable but I think that you will encounter a bunch difficulties with this strategy

I suppose I will have to find strategy that is half way then. I could filter verified options from the JSON tiddler before I forward them to vis.js maybe? Like a white list. Or a black list maybe. This would definitely solve both #4 and #7, and introduce a lot more possibilities all at once, but maybe issues as well... I will give it a try.

**Comment by felixhayashi** [comment]
Hi @kixam 

> I suppose I will have to find strategy that is half way then.

Yap, I agree.

> I could filter verified options from the JSON tiddler before I forward them to vis.js maybe? 

I do the same for TiddlyMap. For example, in case of the network's "manipulation bar".

I make a deepcopy of the user options (loaded from a json tiddler): https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/widget.map.js#L688

But override the "manipulation" property based on whether the user added the editor attribute to the widget: https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/widget.map.js#L708

> Like a white list. Or a black list maybe. 

Yes, you could use `$tw.utils.extend()` to override the user options-object with your forced configuration or do `delete options.optionName` before passing it to `timeline.setOptions()`.

> but maybe issues as well...

The only problem is that users will need to create json tiddlers and sometimes forget to add quotation marks around properties. But this is easy to document and maybe in the future forms or simple config-wizards can be added (to tiddlywiki's control panel).

> I will give it a try.

Nice. If I can be of any help, let me know.

-Felix

**Comment by kixam** [comment]
Fixed in 840128ed0f88648dbd7c4fd5bb03580265f656ef, please test and report bugs!

**Comment by felixhayashi** [comment]
Nice, thanks. I cannot test it now but as soon as I switched to vis v4 I'll report back!

**Comment by kixam** [comment]
hi timeline users,

has anybody tested this feature yet in their own production environment? it is difficult to test all the possible option combinations in all possible situations by just one person.

at least I would appreciate if someone told me this work was useful to them?

**Comment by felixhayashi** [comment]
Hi @kixam 

Sorry for not giving feedback.

I just updated to 0.7.2 and got the following error:

> Uncaught TypeError: Cannot read property 'fields' of undefined
> TimelineWidget.render @ $:/plugins/kixam/timeline/widget.timeline.js:40

Which points at this line of code:

```
this.warningTiddlerTitle = "$:/temp/visjstimeline-warning/" + this.tiddler.fields.title
```

-Felix

**Comment by kixam** [comment]
Hi @felixhayashi ,

I also found this error in some situations, but I cannot yet determine which. Do you use the calendar as a sidebar panel? In my case, I had this error while trying to show the sidebar, but showing the original tiddler in the story was fine. This would be a good lead, but what confuses me is that the demo site works well where my private TW does not, and I cannot find the difference... yet.

**Comment by felixhayashi** [comment]
Hi @kixam 

you are right. It happens because the variable currentTiddler is not set in the sidebar. if you add `<<currentTiddler>>` to a tiddler and have it displayed in the sidebar, the value is empty.

-Felix

**Comment by kixam** [comment]
well, if I cannot get to a tiddler, I might have to make a few changes to some of the functions...

I still hope I can get the original containing tiddler, even from the sidebar. I just have to find another way.

anyway, thank you for the feedback.

**Comment by kixam** [comment]
> Uncaught TypeError: Cannot read property 'fields' of undefined
fixed, see #11

please continue testing the `config` attibute, I need your feedback on this one !

**Comment by kixam** [comment]
> I just updated to 0.7.2 and got the following error

Please see #11

Please resume testing option `config`, I need your feedback :)

**Comment by felixhayashi** [comment]
Hi @kixam 

> Please see #11

Nice. It's fixed!

> Please resume testing option config, I need your feedback :)

of course. I just wanted to wait till you fix the dialog about the missing stardate field :)

**Comment by kixam** [comment]
after 3 months without any complaint, I will consider this a stable feature. Please open another issue if needed
