### ISSUE TITLE
ready for vis v4

### ISSUE THREAD

**Issue by felixhayashi** [kixam/TW5-visjsTimeline#8]
Hi @kixam 

just released tiddlymap with vis v4 and updated the vis plugin repo.

You are good to go ;)

Thanks for the patience!

-Felix

**Comment by kixam** [comment]
thanks, I updated the plugin and the demo site
however, for convenience, I kept my version of vis.js plugin that I compiled from their master branch. I saw you compiled your official plugin from develop branch. I assume there are not many differences?

**Comment by felixhayashi** [comment]
Hi @kixam,

> thanks, I updated the plugin and the demo site

Nice! I am curious to use it and enjoy all the improvements you made :)

> however, for convenience, I kept my version of vis.js plugin that I compiled from their master branch. I saw you compiled your official plugin from develop branch. I assume there are not many differences?

I put the develop version on my repo because the develop branch solved some major issues for the network module. Maybe it is better to clone my vis repo and include it than recompiling it? So if I do some changes to the plugin e.g. add a custom css style for the network module our vis plugins do not conflict...

-Felix

**Comment by kixam** [comment]
Your plugin is the reference for the public, but I have been using vis.js 4.3.0 since it was released so I did not bother downloading your updated plugin, that's all. I will resume doing so at the next release.
