### ISSUE TITLE
Silently ignore no-start-date cases

### ISSUE THREAD

**Issue by felixhayashi** [kixam/TW5-visjsTimeline#9]
Hi @kixam 

I get the same error as described by Sylvain Naudin

https://groups.google.com/d/msg/tiddlywiki/UpxfVI5Zxg8/_88KBoJlNocJ

In my opinion if a tiddler doesn't have a startField (e.g. sometimes the modified field is missing but I use it as start date) it is better to just ignore/skip this tiddler instead of raising an error.

https://github.com/kixam/TW5-visjsTimeline/blob/3264e9990065df43c1779330ca93342bd79a28f6/plugins/timeline/widget.timeline.js#L365

Thanks

-Felix

**Comment by kixam** [comment]
hi @felixhayashi 

In the event an error, for instance the one you encounter, a blue error popup should show, that you can discard. Then the timeline shows, without these tiddlers that raised errors.

This is compliant with emkay's plugin behavior.

Now then, we can deviate from that. But I believe the users would like to know where these tiddlers that match the filter go, if they are not shown on the timeline ? So, how do you suggest I show them what happened?

**Comment by silvyn** [comment]
Thanks @felixhayashi for opening this issue.
@kixam I've updated from 0.6.0 to 0.7.0, and now I've got the blue error popin (was red before).

Maybe I've not anderstand how to add date field correctly. Can you give me an example with value start and end ?

Thanks,
Sylvain

**Comment by felixhayashi** [comment]
Hi @kixam 

> Now then, we can deviate from that. But I believe the users would like to know where these tiddlers that match the filter go, if they are not shown on the timeline? So, how do you suggest I show them what happened?

I understand your point, but often tiddlers just haven't been modified. Still if the user wants to use the timeline plugin with "startDate" being "modified", should the user always give all tiddlers a modified field to avoid being confronted with alerts? Also, how should the user solve this? Opening the tiddler and add a modification date manually (in a difficult format; unfortunately no date picker exists for tw)? Or should the user edit the tiddler and close it again to artificially set the modification date to "now"?

IMO it is better to hide the tiddler in the timeline and clearly describe this in the docs than to raise a message. Of course best would be to raise a message with an option "don't show this again" - but this would require you to spend time implementing this... You can also add a tiddler that acts as flag that you raised an alert and not show it again.

-Felix

**Comment by kixam** [comment]
Hi @silvyn ,

> Can you give me an example with value start and end ?

Like @felixhayashi said, `created` and `modified` fields are automatically and transparently handled by TiddlyWiki, so you should not have to do anything to create/modify them. Actually, you should not modify them manually.

Also, by default i.e. if you call the widget without attributes, e.g. `<$visjstimeline />`, the start date field is set to `created`, and no end date field will be used. If you want to use `modified` as the end date field, you have to specify it, like so: `<$visjstimeline endDateField="modified" />`.

Now, if you want to use your own fields, with your own format, you can call the widget with more attributes, e.g. `<$visjstimeline startDateField="start" endDateField="end" format="YYYY-MM-DD" />`, which will make the widget look for fields named "start" and "end" in all filtered tiddlers (you have to create/edit these yourself), and assume their value is formatted like you specified, e.g. in this example, "2015-07-02" is correct, but "02/07/05" is not.

Hi @felixhayashi ,

> Of course best would be to raise a message with an option "don't show this again"

I think this is the course I would rather look into. Maybe this weekend.

> unfortunately no date picker exists for tw

I started looking into this as well. Do you know if @Jermolene intends to implement this feature into the core ?

**Comment by felixhayashi** [comment]
> I started looking into this as well. Do you know if @Jermolene intends to implement this feature into the core ?

No, he wants to wait until it is natively supported by browsers...

> My view on date pickers is the same as on color pickers: the core should support HTML date pickers when they are widely supported by browsers (they are not at the moment: http://caniuse.com/#feat=input-datetime). If we want a date picker in the meantime then it should be a plugin so that we can migrate it gracefully.
> 
> See: https://github.com/Jermolene/TiddlyWiki5/issues/1449

**Comment by Jermolene** [comment]
> No, he wants to wait until it is natively supported by browsers...

That's only for the core; what I'd really love for the moment is a plugin that provides a decent date/time picker.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> That's only for the core; what I'd really love for the moment is a plugin that provides a decent date/time picker.

Oh, sorry for misundersting your point then and thanks for clarifying.

**Comment by kixam** [comment]
Fixed in f08deb4505c13e3fb79b828a0e041f7a420cdec0

**Comment by silvyn** [comment]
Thanks @kixam, I've just test 0.7.2 and can play successfully :)
(like $:/temp/visjstimeline-warning/nametiddler which help user where he has forget something).

**Comment by kixam** [comment]
hi @silvyn ,

thank you for your feedback :)

**Comment by silvyn** [comment]
Oh ! Sound great TW5-datePicker @kixam !
https://github.com/kixam/TW5-datePicker

(poke @Jermolene)

**Comment by kixam** [comment]
the datePicker plugin is not yet functional, please be patient!

**Comment by felixhayashi** [comment]
@kixam 

Very nice solution with the red warning icon!

-Felix

**Comment by kixam** [comment]
thanks, feel free to get inspiration from it for your own needs ;)
